{% set name = "napari-psf-simulator" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-psf-simulator-{{ version }}.tar.gz
  sha256: e131284b801c91194c72d1a9993c0f2b40110dac5c650690e696c91d1da12742

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - magicgui
    - napari
    - numpy
    - python >=3.8
    - qtpy
    - scipy

test:
  imports:
    - napari_psf_simulator
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/andreabassi78/napari-psf-simulator
  summary: A plugin for simulations of the Point Spread Function, with aberrations
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andreabassi78
    - goanpeca
    - jaimergp
