{% set name = "napari-psf-simulator" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-psf-simulator-{{ version }}.tar.gz
  sha256: d92a3613b9dff79e892c30ef79f95ce828f9d35c40b009667b9f1f69d3da36f3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8,<3.11
    - setuptools-scm
  run:
    - magicgui
    - matplotlib-base
    - napari
    - numpy
    - pycustomfocus >=3.3.6
    - python >=3.8,<3.11
    - qtpy
    - scikit-image  # Imported but not required
    - scipy   # Imported but not required

test:
  imports:
    - napari_psf_simulator
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/napari-psf-simulator
  summary: A plugin for simulations of the Point Spread Function, with aberrations
  license: BSD-3-Clause
  license_file: LICENSE
  dev_urel: https://github.com/andreabassi78/napari-psf-simulator

extra:
  recipe-maintainers:
    - andreabassi78
    - goanpeca
    - jaimergp
